name: docker
on: push

jobs:
  docker-ps:
    runs-on: ubuntu-latest
    container: node:14.16
    steps:
      - name: check nodes version
        run: |
          node -v
          cat /etc/os-release
          
