name: docker
on: push

jobs:
  docker-ps:
    runs-on: ubuntu-latest
    container: node:14.16
    steps:
      - name: docker install
        run: |
          apt update -y
          apt install apt-transport-https ca-certificates curl software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt-cache policy docker-ce
          apt install docker-ce -y
          systemctl status docker

      - name: docker login
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PASSWORD 
      - name: check nodes version
        run: |
          node -v
          cat /etc/os-release
          
