name: docker
on: push

jobs:
  docker-ps:
    runs-on: ubuntu-latest
    container: node:14.16
    steps:
      - name: docker login
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PASSWORD 
      - name: check nodes version
        run: |
          node -v
          cat /etc/os-release
          
