name: docker-node
on: push

jobs:
  docker-node:
    runs-on: ubuntu-latest
    steps:
      - name: echo using entrypoint
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World"
      - name: echo node version
        uses:
          entrypoint: "/usr/local/bin/node"
          args: "-v"


