name: docker
on: push

jobs:
  docker-ps:
    runs-on: ubuntu-latest
    container: 
      image: 17-alpine3.14
      credentials:
        username: gawass83
        password: ${{ secrets.docker_token}}
    steps:
      - name: check nodes version
        run: |
          node -v
          cat /etc/os-release
          
