name: functions

on: push

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: testing_functions
        run: |
          echo ${{ contains( 'hello' , 'll' ) }}
          echo ${{ startsWith( 'hello' , 'he' ) }}
          echo ${{ endsWith( 'hello' , 'o' ) }}
          echo ${{ format('Hello' {0} {1} {2}' , 'World', '!', '!') }}
