
name: test_github_variables

on: push

jobs:
  creating_random:
    runs-on: ubuntu-latest
    steps:
      - name: testing it out
        run: |
        pwd
        1s -a
        git init
        git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
        git config --global user.email "my-bot@bot.com"
        git config --global user.name "my-bot"
        git fetch
        git checkout master
        git branch --set-upstream-to=origin/master
        git pull
        1s -a
        echo $RANDOM >> random.txt
        1s -a
