name: strategy
on: push
jobs:
  strategy-task:
    strategy:
      matrix:
        os: [mac-os-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]
        exclude:
        -  os: ubuntu-latest
           node_version: 8
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node_version }}
      - name: check node version
        run: node -v
    
        
  
